name: Delete
on:
  workflow_dispatch:
    inputs:
      fileName:
        required: true
jobs:
  task:
    runs-on: ubuntu-latest
    env:
      FIREBASE_CREDENTIAL_TOKEN: ${{ secrets.FIREBASE_CREDENTIAL_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - name: Installing Dependencies
        run: npm install
      - name: Downloading Video
      - name: Uploading Video
        run: node delete.js '${{ github.event.inputs.fileName }}'
