name: Download
on:
  workflow_dispatch:
    inputs:
      source:
        required: true
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - name: Installing Dependencies
        run: npm install
      - name: Downloading Video
        run: curl -L '${{ github.event.inputs.source }}' -o 'videoplayback.mp4' --progress-bar
      - name: Uploading Video
        run: node index.js
