name: Download stream video to cloud storage
on:
  workflow_dispatch:
    inputs:
      source:
        required: true
      title:
        required: true
        default: videoplayback.mp4
jobs:
  task:
    runs-on: ubuntu-latest
    env:
      FIREBASE_CREDENTIAL_URL: ${{ secrets.FIREBASE_CREDENTIAL_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: FFMPEG
        uses: FedericoCarboni/setup-ffmpeg@v1
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - name: Download
        run: ffmpeg -y -i '${{ github.event.inputs.source }}' -c:v libx264 -c:a aac '${{ github.event.inputs.title }}'
      - name: Install
        run: yarn
      - name: Upload
        run: node main.js
